export type MenuItemConfig = {
  key: string;
  label: string;
  icon?: string;
  path?: string; // leaf only
  requiresAny?: string[]; // permissions
  children?: MenuItemConfig[];
};

export const MENU_REGISTRY: MenuItemConfig[] = [
  // ---------------- Core ----------------
  {
    key: "core",
    label: "Dashboard",
    icon: "HomeOutlined",
    children: [
      {
        key: "home",
        label: "Home",
        path: "/home",
        icon: "HomeOutlined",
        requiresAny: ["home.view"],
      },
      {
        key: "calendar",
        label: "Calendar",
        path: "/calendar",
        icon: "CalendarOutlined",
        requiresAny: ["calendar.view"],
      },
    ],
  },

  // ---------------- Organization & Masters ----------------
  {
    key: "org_masters",
    label: "Organization",
    icon: "BankOutlined",
    children: [
      {
        key: "organization.view",
        label: "Organization",
        path: "/organization/view",
        icon: "BankOutlined",
        requiresAny: ["org.view"],
      },
      {
        key: "attendance.view",
        label: " Attendance",
        path: "/attendance",
        icon: "FieldTimeOutlined",
        requiresAny: ["attendance.view"],
      },
      {
        key: "leaves.view",
        label: "Leaves",
        path: "/leaves",
        icon: "CalendarOutlined",
        requiresAny: ["leaves.view"],
      },
      {
        key: "interactions",
        label: "Events",
        path: "/events",
        requiresAny: ["interactions.view"],
        icon: "ScheduleOutlined",
      },
      {
        key: "tag.create",
        label: "Create Tag",
        path: "/tags/create",
        icon: "PlusOutlined",
        requiresAny: ["tag.create"],
      },
      {
        key: "tag.view",
        label: "View Tag",
        path: "/tags",
        icon: "EyeOutlined",
        requiresAny: ["tag.view"],
      },
      {
        key: "productCatalog.create",
        label: "Create Item Master",
        path: "/product-catalog/create",
        icon: "PlusOutlined",
        requiresAny: ["product_catalog.create"],
      },
      {
        key: "productCatalog.view",
        label: "View Item Master",
        path: "/product-catalog",
        icon: "AppstoreOutlined",
        requiresAny: ["product_catalog.view"],
      },
      {
        key: "productCatalog.import",
        label: "Import",
        path: "/product-catalog/import",
        icon: "ImportOutlined",
        requiresAny: ["product_catalog.import"],
      },
    ],
  },

  // ---------------- Sales ----------------
  {
    key: "sales",
    label: "Sales",
    icon: "TeamOutlined",
    children: [
      {
        key: "contacts.createFromVCard",
        label: "Create Contact From vCard",
        path: "/contacts/create-from-vcard",
        icon: "PlusOutlined",
        requiresAny: ["contacts.create_from_vcard"],
      },
      {
        key: "contacts.view",
        label: "Contacts",
        path: "/contacts",
        icon: "ContactsOutlined",
        requiresAny: ["contacts.view"],
      },
      {
        key: "contacts.import",
        label: "Import Contacts",
        path: "/contacts/import",
        icon: "ImportOutlined",
        requiresAny: ["contacts.import"],
      },
      {
        key: "contacts.recent",
        label: "Recently Viewed",
        path: "/contacts/recent",
        icon: "HistoryOutlined",
        requiresAny: ["contacts.recent"],
      },
      {
        key: "leads.createFromCard",
        label: "Create Lead From Card",
        path: "/leads/create-from-card",
        icon: "PlusOutlined",
        requiresAny: ["leads.create_from_card"],
      },
      {
        key: "leads.view",
        label: "Leads",
        path: "/leads/view",
        icon: "FireOutlined",
        requiresAny: ["leads.view"],
      },
      {
        key: "leads.import",
        label: "Import Leads",
        path: "/leads/import",
        icon: "ImportOutlined",
        requiresAny: ["leads.import"],
      },
      {
        key: "leads.recent",
        label: "Recently Viewed",
        path: "/leads/recent",
        icon: "HistoryOutlined",
        requiresAny: ["leads.recent"],
      },
      {
        key: "opportunities.view",
        label: " Opportunities",
        path: "/opportunities",
        icon: "TrophyOutlined",
        requiresAny: ["opportunities.view"],
      },
      {
        key: "opportunities.import",
        label: "Import Opportunities",
        path: "/opportunities/import",
        icon: "ImportOutlined",
        requiresAny: ["opportunities.import"],
      },
      {
        key: "quotes.view",
        label: " Quotes",
        path: "/quotes",
        icon: "FileProtectOutlined",
        requiresAny: ["quotes.view"],
      },
      {
        key: "quotes.import",
        label: "Import",
        path: "/quotes/import",
        icon: "ImportOutlined",
        requiresAny: ["quotes.import"],
      },
      {
        key: "quotes.importLineItems",
        label: "Import Line Items",
        path: "/quotes/import-line-items",
        icon: "ImportOutlined",
        requiresAny: ["quotes.import_line_items"],
      },
      {
        key: "delivery_challans.view",
        label: "Delivery Challans",
        path: "/delivery-challans",
        icon: "TruckOutlined",
        requiresAny: ["delivery_challans.view"],
      },
    ],
  },

  {
    key: "tally-operations",
    label: "Accounts",
    icon: "AuditOutlined",
    requiresAny: ["tally-operations.view"],
    children: [
      {
        key: "purchase-orders.view",
        label: "Purchase Orders",
        path: "/purchase-orders",
        icon: "ShoppingOutlined",
        requiresAny: ["purchase-orders.view"],
      },
      {
        key: "sales-orders.view",
        label: "Sales Orders",
        path: "/sales-orders",
        icon: "SolutionOutlined",
        requiresAny: ["sales-orders.view"],
      },
      {
        key: "tally-performance.view",
        label: "Tally Performance",
        path: "/tally-performance",
        icon: "FundProjectionScreenOutlined",
        requiresAny: ["tally-performance.view"],
      },
      {
        key: "tally-employees.view",
        label: "Tally Employees",
        path: "/tally-employees",
        icon: "FundProjectionScreenOutlined",
        requiresAny: ["tally-employees.view"],
      },
    ],
  },

  // ---------------- Operations ----------------
  {
    key: "operations",
    label: "Operations",
    icon: "ScheduleOutlined",
    children: [
      {
        key: "my-day",
        label: "My Day",
        path: "/my-day",
        icon: "ScheduleOutlined",
        requiresAny: [
          "dashboard.view",
          "tasks.view",
          "leads.view",
          "my-day.view",
        ],
      },
      {
        key: "emails.compose",
        label: "Compose",
        path: "/emails/compose",
        icon: "PlusOutlined",
        requiresAny: ["emails.compose"],
      },
      {
        key: "emails.view",
        label: "View Email",
        path: "/emails",
        icon: "EyeOutlined",
        requiresAny: ["emails.view"],
      },
      {
        key: "calls.log",
        label: "Log Call",
        path: "/calls/log",
        icon: "PlusOutlined",
        requiresAny: ["calls.log"],
      },
      {
        key: "calls.import",
        label: "Import Calls",
        path: "/calls/import",
        icon: "ImportOutlined",
        requiresAny: ["calls.import"],
      },
      {
        key: "products.view",
        label: "Products",
        path: "/products",
        icon: "AppstoreOutlined",
        requiresAny: ["products.view"],
      },
      {
        key: "meetings.schedule",
        label: "Schedule Meeting",
        path: "/meetings/schedule",
        icon: "PlusOutlined",
        requiresAny: ["meetings.schedule"],
      },
      {
        key: "meetings.view",
        label: "View Meetings",
        path: "/meetings",
        icon: "EyeOutlined",
        requiresAny: ["meetings.view"],
      },
      {
        key: "meetings.import",
        label: "Import Meetings",
        path: "/meetings/import",
        icon: "ImportOutlined",
        requiresAny: ["meetings.import"],
      },
      {
        key: "tasks.view",
        label: "Tasks",
        path: "/tasks",
        icon: "CheckSquareOutlined",
        requiresAny: ["tasks.view"],
      },

      {
        key: "notes.create",
        label: "Create Note or Attachment",
        path: "/notes/create",
        icon: "PlusOutlined",
        requiresAny: ["notes.create"],
      },
      {
        key: "notes.view",
        label: "View Notes",
        path: "/notes",
        icon: "EyeOutlined",
        requiresAny: ["notes.view"],
      },
      {
        key: "notes.import",
        label: "Import Notes",
        path: "/notes/import",
        icon: "ImportOutlined",
        requiresAny: ["notes.import"],
      },
      {
        key: "cases.create",
        label: "Create Case",
        path: "/cases/create",
        icon: "PlusOutlined",
        requiresAny: ["cases.create"],
      },
      {
        key: "cases.view",
        label: "View Cases",
        path: "/cases",
        icon: "EyeOutlined",
        requiresAny: ["cases.view"],
      },
      {
        key: "cases.import",
        label: "Import Cases",
        path: "/cases/import",
        icon: "ImportOutlined",
        requiresAny: ["cases.import"],
      },
      {
        key: "visit.view",
        label: "Visits",
        path: "/visits",
        icon: "EnvironmentOutlined",
        requiresAny: ["visits.view"],
      },
      {
        key: "visit.import",
        label: "Import",
        path: "/visit/import",
        icon: "ImportOutlined",
        requiresAny: ["visit.import"],
      },
      {
        key: "visitSummary.create",
        label: "Create VisitSummary",
        path: "/visit-summary/create",
        icon: "PlusOutlined",
        requiresAny: ["visit_summary.create"],
      },
      {
        key: "visitSummary.view",
        label: "View VisitSummary",
        path: "/visit-summary",
        icon: "EyeOutlined",
        requiresAny: ["visit_summary.view"],
      },
    ],
  },

  // ---------------- Reports & Templates ----------------
  // {
  //   key: "reports_templates",
  //   label: "Reports & Templates",
  //   icon: "BarChartOutlined",
  //   children: [
  //     {
  //       key: "pdfTemplates.create",
  //       label: "Create PDF Template",
  //       path: "/pdf-templates/create",
  //       icon: "PlusOutlined",
  //       requiresAny: ["pdf_templates.create"],
  //     },
  //     {
  //       key: "pdfTemplates.view",
  //       label: "View PDF Templates",
  //       path: "/pdf-templates",
  //       icon: "EyeOutlined",
  //       requiresAny: ["pdf_templates.view"],
  //     },
  //     {
  //       key: "pdfTemplates.import",
  //       label: "Import",
  //       path: "/pdf-templates/import",
  //       icon: "ImportOutlined",
  //       requiresAny: ["pdf_templates.import"],
  //     },
  //     {
  //       key: "dreamReports.create",
  //       label: "Create Reports",
  //       path: "/dream-reports/create",
  //       icon: "PlusOutlined",
  //       requiresAny: ["dream_reports.create"],
  //     },
  //     {
  //       key: "dreamReports.view",
  //       label: "View Reports",
  //       path: "/dream-reports",
  //       icon: "EyeOutlined",
  //       requiresAny: ["dream_reports.view"],
  //     },
  //     {
  //       key: "emailTemplates.create",
  //       label: "Create Email Template",
  //       path: "/email-templates/create",
  //       icon: "PlusOutlined",
  //       requiresAny: ["email_templates.create"],
  //     },
  //     {
  //       key: "emailTemplates.view",
  //       label: "View Email Templates",
  //       path: "/email-templates",
  //       icon: "EyeOutlined",
  //       requiresAny: ["email_templates.view"],
  //     },
  //     {
  //       key: "holidays",
  //       label: "Holidays",
  //       path: "/holidays",
  //       icon: "GiftOutlined",
  //       requiresAny: ["holidays.view"],
  //     },
  //     {
  //       key: "subTask",
  //       label: "Sub Task",
  //       path: "/sub-task",
  //       icon: "PartitionOutlined",
  //       requiresAny: ["sub_task.view"],
  //     },
  //   ],
  // },

  // ---------------- Settings ----------------
  {
    key: "settings",
    label: "Settings",
    icon: "SettingOutlined",
    children: [
      {
        key: "rbac.view",
        label: "RBAC",
        path: "/rbac",
        icon: "SafetyCertificateOutlined",
        requiresAny: ["rbac.view"],
      },
      {
        key: "users.create",
        label: "Create User",
        path: "/users/create",
        icon: "PlusOutlined",
        requiresAny: ["users.create"],
      },
      {
        key: "users.view",
        label: " Users",
        path: "/users",
        icon: "TeamOutlined",
        requiresAny: ["users.view"],
      },
      {
        key: "users.import",
        label: "Import",
        path: "/users/import",
        icon: "ImportOutlined",
        requiresAny: ["users.import"],
      },
      {
        key: "imports.create",
        label: "Create Import",
        path: "/imports/create",
        icon: "PlusOutlined",
        requiresAny: ["imports.create"],
      },
      {
        key: "imports.view",
        label: "View Imports",
        path: "/imports",
        icon: "CloudUploadOutlined",
        requiresAny: ["imports.view"],
      },
      {
        key: "imports.import",
        label: "Import",
        path: "/imports/import",
        icon: "ImportOutlined",
        requiresAny: ["imports.import"],
      },
      {
        key: "roles.create",
        label: "Create Role",
        path: "/roles/create",
        icon: "PlusOutlined",
        requiresAny: ["roles.create"],
      },
      {
        key: "roles.view",
        label: "View Roles",
        path: "/roles",
        icon: "EyeOutlined",
        requiresAny: ["roles.view"],
      },
      {
        key: "roles.import",
        label: "Import",
        path: "/roles/import",
        icon: "ImportOutlined",
        requiresAny: ["roles.import"],
      },
      {
        key: "departments.create",
        label: "Create Department",
        path: "/departments/create",
        icon: "PlusOutlined",
        requiresAny: ["departments.create"],
      },
      {
        key: "departments.view",
        label: "View Departments",
        path: "/departments",
        icon: "EyeOutlined",
        requiresAny: ["departments.view"],
      },
      {
        key: "departments.import",
        label: "Import",
        path: "/departments/import",
        icon: "ImportOutlined",
        requiresAny: ["departments.import"],
      },
      {
        key: "locations.create",
        label: "Create Location",
        path: "/locations/create",
        icon: "PlusOutlined",
        requiresAny: ["locations.create"],
      },
      {
        key: "locations.view",
        label: "View Locations",
        path: "/locations",
        icon: "EyeOutlined",
        requiresAny: ["locations.view"],
      },
      {
        key: "locations.import",
        label: "Import",
        path: "/locations/import",
        icon: "ImportOutlined",
        requiresAny: ["locations.import"],
      },
      {
        key: "products.import",
        label: "Import",
        path: "/products/import",
        icon: "ImportOutlined",
        requiresAny: ["products.import"],
      },
      {
        key: "productCategories.create",
        label: "Create Product Category",
        path: "/product-categories/create",
        icon: "PlusOutlined",
        requiresAny: ["product_categories.create"],
      },
      {
        key: "productCategories.view",
        label: "View Product Categories",
        path: "/product-categories",
        icon: "EyeOutlined",
        requiresAny: ["product_categories.view"],
      },
      {
        key: "productCategories.import",
        label: "Import",
        path: "/product-categories/import",
        icon: "ImportOutlined",
        requiresAny: ["product_categories.import"],
      },
      {
        key: "productGroups.create",
        label: "Create Product Group",
        path: "/product-groups/create",
        icon: "PlusOutlined",
        requiresAny: ["product_groups.create"],
      },
      {
        key: "productGroups.view",
        label: "View Product Groups",
        path: "/product-groups",
        icon: "EyeOutlined",
        requiresAny: ["product_groups.view"],
      },
      {
        key: "productGroups.import",
        label: "Import",
        path: "/product-groups/import",
        icon: "ImportOutlined",
        requiresAny: ["product_groups.import"],
      },
      {
        key: "productSubCategories.create",
        label: "Create Product Sub-Category",
        path: "/product-sub-categories/create",
        icon: "PlusOutlined",
        requiresAny: ["product_sub_categories.create"],
      },
      {
        key: "productSubCategories.view",
        label: "View Product Sub-Categories",
        path: "/product-sub-categories",
        icon: "EyeOutlined",
        requiresAny: ["product_sub_categories.view"],
      },
      {
        key: "productSubCategories.import",
        label: "Import",
        path: "/product-sub-categories/import",
        icon: "ImportOutlined",
        requiresAny: ["product_sub_categories.import"],
      },
      {
        key: "productTypes.create",
        label: "Create Product Type",
        path: "/product-types/create",
        icon: "PlusOutlined",
        requiresAny: ["product_types.create"],
      },
      {
        key: "productTypes.view",
        label: "View Product Types",
        path: "/product-types",
        icon: "EyeOutlined",
        requiresAny: ["product_types.view"],
      },
      {
        key: "productTypes.import",
        label: "Import",
        path: "/product-types/import",
        icon: "ImportOutlined",
        requiresAny: ["product_types.import"],
      },
    ],
  },
];
